

GRANT SELECT ON EMPLOYEES TO WEB;


부여한 SELECT 권한을 회수
REVOKE SELECT ON EMPLOYEES FROM WEB;

GRANT SELECT ON EMPLOYEES TO MROLE2;
GRANT SELECT ON DEPARTMENTS TO MROLE2;
GRANT SELECT ON LOCATIONS TO MROLE2;

