
-- INSERT => 테이블에 새로운 행을 추가
INSERT INTO DEPT01
(DEPTNO, DNAME, LOC)
VALUES(10, 'ACCOUNTING', 'NEW YORK');

INSERT INTO DEPT01
(DEPTNO, DNAME, LOC)
VALUES(10, 'ACCOUNTINGAAAAAAAAAAAAAAAAAAAAAAAAAAAA', 'NEW YORK'); -- 데이터 형식에 맞지 않을 시 에러 발생
SELECT * FROM DEPT01;

INSERT INTO DEPT01
VALUES(20, 'RESEARCH', 'NEW YORK');

-- NULL 삽입
INSERT INTO DEPT01
(DEPTNO, DNAME)
VALUES(30, 'SALES');  -- 암시적 삽입

INSERT INTO DEPT01
VALUES(40, 'OPERATION', NULL); -- 명시적 삽입



-- INSERT => 테이블에 새로운 행을 추가
INSERT INTO DEPT01
(DEPTNO, DNAME, LOC)
VALUES(10, 'ACCOUNTING', 'NEW YORK');

INSERT INTO DEPT01
(DEPTNO, DNAME, LOC)
VALUES(10, 'ACCOUNTINGAAAAAAAAAAAAAAAAAAAAAAAAAAAA', 'NEW YORK'); -- 데이터 형식에 맞지 않을 시 에러 발생
SELECT * FROM DEPT01;

INSERT INTO DEPT01
VALUES(20, 'RESEARCH', 'NEW YORK');

-- NULL 삽입
INSERT INTO DEPT01
(DEPTNO, DNAME)
VALUES(30, 'SALES');  -- 암시적 삽입

INSERT INTO DEPT01
VALUES(40, 'OPERATION', NULL); -- 명시적 삽입



CREATE TABLE EMP01 (
        EMPNO NUMBER(4),
        ENMAE VARCHAR2(20),
        SAL NUMBER(7,2),
        REG_DATE DATE
);

INSERT INTO EMP01
VALUES(1, '홍길동', 1000, SYSDATE);
SELECT * FROM EMP01;

-- 서브쿼리로 데이터 삽입하기
DROP TABLE DEPT02;
CREATE TABLE DET02
AS
SELECT * FROM DEPARTMENTS WHERE 1=0;

INSERT INTO DEPT02
SELECT * FROM DEPARTMENTS;

-- UPDATE-SET-WHERE => 테이블의 내용을 수정
DROP TABLE EMP01;
CREATE TABLE EMP01
AS
SELECT * FROM EMPLOYEES;

UPDATE EMP01
SET DEPARTMENT_ID=30;

SELECT * FROM EMP01;

-- 모든 사원의 급여를 10% 인상
UPDATE EMP01
SET SALARY = SALARY * 1.1;

-- 모든 사원의 입사일을 오늘로 수정
UPDATE EMP01
SET HIRE_DATE = SYSDATE;
-- 특정 행 변경
DESC EMP01;

UPDATE EMP01
SET SALARY = SALARY * 1.1
WHERE SALARY >= 3000;

-- 2003년 입사한 사원의 입사일을 오늘로 수정
DROP TABLE EMP01;
CREATE TABLE EMP01
AS
SELECT * FROM EMPLOYEES;

UPDATE EMP01
SET HIRE_DATE = SYSDATE
WHERE SUBSTR(HIRE_DATE, 1, 2) = '03';

UPDATE EMP01
SET SALARY = SALARY-5000
WHERE SALARY > 10000;

-- 테이블에서 2개 이상의 컬럼값 변경 시
DROP TABLE EMP01;
CREATE TABLE EMP01
AS
SELECT * FROM EMPLOYEES;

UPDATE EMP01
SET DEPARTMENT_ID = 20,
    JOB_ID = 'AC_MER'
WHERE LAST_NAME='Jones';

SELECT * FROM EMP01
WHERE LAST_NAME='Jones';

-- 서브 쿼리를 이용한 데이터 수정 => 단일 행의 서브 쿼리
UPDATE DEPT01
SET (DNAME, LOC) = (
            SELECT DNAME, LOC
            FROM DEPT01
            WHERE DEPTINO=10)
WHERE DEPTNO=30;

-- EMP01의 모든 사원의 급여와 입사일을 Jones인 사원의 급여와 입사일과 같게 변경
UPDATE EMP01
SET (SALARY, HIRE_DATE) = (
                SELECT SALARY, HIRE_DATE
                FROM EMP01
                WHERE LAST_NAME='Jones');
SELECT * FROM EMP01;
-- LONDON에 있는 모든 직원의 월급을 1000 인상

-- DELETE 문 => 행을 삭제
DROP TABLE DEPT02;
CREATE TABLE DEPT02
AS
SELECT * FROM DEPT01;

DELETE FROM DEPT02;
