
-- ROWID
select rowid, rownum, employee_id
from employees;

-- CREATE TABLE
CREATE TABLE EMP01 (
        EMPNO NUMBER(4),
        ENMAE VARCHAR2(20),
        SAL NUMBER(7,2));
        
SELECT * FROM EMP01;
DESC EMP01;

CREATE TABLE DEPT01 (
        DEPTNO NUMBER(2),
        DNAME VARCHAR2(14),
        LOC VARCHAR2(13)
);

DESC DEPT01;

-- 서브쿼리로 테이블을 만드는 경우 이미 존재하는 테이블과 동일한 구조와 내용을 갖는 새로운 테이블 생성 가능
CREATE TABLE EMP02
AS
SELECT * FROM EMPLOYEES;
SELECT * FROM EMP02;

CREATE TABLE EMP03
AS
SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME FROM EMPLOYEES;
SELECT * FROM EMP03;

CREATE TABLE EMP04
AS
SELECT * FROM EMPLOYEES
WHERE DEPARTMENT_ID=80;
SELECT * FROM EMP04;

CREATE TABLE EMP05
AS
SELECT * FROM EMPLOYEES
ORDER BY DEPARTMENT_ID DESC;
SELECT ROWNUM, DEPARTMENT_ID FROM EMP05;

-- DEPARTMENT 테이블과 동일 구조만 복제
CREATE TABLE DEPT
AS
SELECT * FROM DEPARTMENTS
WHERE 1=0;  -- 틀린 조건을 줄 경우 조건에 해당하는 데이터가 없기 때문에 구조만 생성
SELECT * FROM DEPT;


-- ALTER TABLE => 테이블 구조를 변경
DESC EMP01;
ALTER TABLE EMP01
ADD(JOB VARCHAR2(9));
DESC EMP01;

ALTER TABLE DEPT01
ADD(DMGR VARCHAR2(10));
DESC DEPT01;

-- ALTER TABLE: 기존 컬럼의 속성 변경하기 - 컬럼에 데이터가 있는 경우 크기 늘리기만 가능
ALTER TABLE EMP01
MODIFY(JOB VARCHAR2(30));
DESC EMP01;

ALTER TABLE DEPT01
MODIFY(DMGR NUMBER(4));
DESC DEPT01;
-- DROP: 컬럼 삭제
ALTER TABLE DEPT01
DROP COLUMN DMGR;
DESC DEPT01;
-- SET UNUSED 컬럼의 사용을 논리적으로 제한 => 운영 중 삭제해야 할 컬럼이 있을 경우 사용
ALTER TABLE EMP02
SET UNUSED(JOB_ID);
SELECT * FROM EMP02;

DESC EMP02;

ALTER TABLE EMP02
DROP UNUSED COLUMNS; -- 사용 제한한 컬럼 삭제

-- DROP TABLE: 테이블 삭제
DROP TABLE EMP01;
SELECT * FROM EMP01;

-- TRUNCATE TABLE 테이블의 데이터 삭제(구조는 유지), 복원 불가
TRUNCATE TABLE EMP02;
SELECT * FROM EMP02;

-- RENAME
RENAME EMP02 TO TEST;
SELECT * FROM EMP02;
SELECT * FROM TEST;


SELECT * FROM TAB;
-- USER_데이터 딕셔너리: 자신의 계정이 소유한 객체 등에 관한 정보 조회
DESC USER_TABLES; -- USER_TABLES: 현재 접속한 테이블 정보 조회
SELECT TABLE_NAME FROM USER_TABLES  
WHERE TABLE_NAME = 'EMPLOYEES'; -- 테이블명이 소문자일 경우 조회되지 않음