create table emp (
  empno number);

-- 다른 사용자의 객체 사용 시 콤마 사용. HR계정에서 SELECT 접근 권한을 부여하고 해당 쿼리를 실행.
SELECT * FROM HR.EMPLOYEES;


-- 회원 테이블 생성
DROP TABLE MEMBER;
CREATE TABLE MEMBER(
  USER_ID VARCHAR2(10) PRIMARY KEY,
  PASSWORD VARCHAR2(256),
  NAME VARCHAR2(20 CHAR),
  EMAIL VARCHAR2(64),
  PHONE VARCHAR2(20),
  ADDRESS VARCHAR2(100 CHAR),
  REG_DATE DATE DEFAULT SYSDATE,
  UPDATE_DATE DATE DEFAULT SYSDATE
);

INSERT INTO MEMBER
SELECT LOWER(EMAIL), '1234', LAST_NAME, LOWER(EMAIL) || '@naver.com',
  REPLACE(PHONE_NUMBER, '.', '-'), NULL, HIRE_DATE, SYSDATE
FROM HR.EMPLOYEES;

SELECT * FROM MEMBER;


-- 동의어
SELECT * FROM SYS.SYSTBL;
CREATE SYNONYM PriSYSTBL FOR SYS.SYSTBL;
SELECT * FROM PriSYSTBL;
SELECT * FROM PUBDEPT;

